apiVersion: v2
name: devops-automation
description: A Helm chart for DevOps Automation Platform

# This is the chart version
version: 0.1.0

# This is the version number of the application being deployed
appVersion: "1.0.0"

dependencies:
  - name: prometheus
    version: 15.10.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 6.32.2
    repository: https://grafana.github.io/helm-charts
